[package]
name = "rustlearning"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = {version = "0.55.1",features = ["async","proc_macro"]}
rand = "0.9.1"
tokio = { version = "1.45.0", features = ["full"] }
